steps:
  LOAD_GW_BC_PROD_BC_USERSETTINGS-200022876:
    operation:
      config:
        insertStrategy: INSERT
        postSQL: ""
        preSQL: ""
        testsEnabled: true
        truncateBefore: true
      database: ""
      dependencies: []
      deployEnabled: true
      description: ""
      isMultisource: false
      locationID: 20000013
      locationName: LOAD
      materializationType: table
      metadata:
        columns:
          - columnReference:
              columnCounter: 2000127352
              stepCounter: "200022876"
            dataType: BOOLEAN
            defaultValue: ""
            description: ""
            name: ROTATETABLES
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"BC_USERSETTINGS\".\"ROTATETABLES\""
          - columnReference:
              columnCounter: 2000127353
              stepCounter: "200022876"
            dataType: NUMBER(38)
            defaultValue: ""
            description: ""
            name: LOADCOMMANDID
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"BC_USERSETTINGS\".\"LOADCOMMANDID\""
          - columnReference:
              columnCounter: 2000127354
              stepCounter: "200022876"
            dataType: NUMBER(38)
            defaultValue: ""
            description: ""
            name: CREATEUSERID
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"BC_USERSETTINGS\".\"CREATEUSERID\""
          - columnReference:
              columnCounter: 2000127355
              stepCounter: "200022876"
            dataType: VARCHAR(64)
            defaultValue: ""
            description: ""
            name: PUBLICID
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"BC_USERSETTINGS\".\"PUBLICID\""
          - columnReference:
              columnCounter: 2000127356
              stepCounter: "200022876"
            dataType: NUMBER(38)
            defaultValue: ""
            description: ""
            name: BEANVERSION
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"BC_USERSETTINGS\".\"BEANVERSION\""
          - columnReference:
              columnCounter: 2000127357
              stepCounter: "200022876"
            dataType: TIMESTAMP
            defaultValue: ""
            description: ""
            name: CANCELALERTDISMISS
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"BC_USERSETTINGS\".\"CANCELALERTDISMISS\""
          - columnReference:
              columnCounter: 2000127358
              stepCounter: "200022876"
            dataType: BOOLEAN
            defaultValue: ""
            description: ""
            name: PRINTPAGENUMS
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"BC_USERSETTINGS\".\"PRINTPAGENUMS\""
          - columnReference:
              columnCounter: 2000127359
              stepCounter: "200022876"
            dataType: NUMBER(38)
            defaultValue: ""
            description: ""
            name: RETIRED
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"BC_USERSETTINGS\".\"RETIRED\""
          - columnReference:
              columnCounter: 2000127360
              stepCounter: "200022876"
            dataType: TIMESTAMP
            defaultValue: ""
            description: ""
            name: CREATETIME
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"BC_USERSETTINGS\".\"CREATETIME\""
          - columnReference:
              columnCounter: 2000127361
              stepCounter: "200022876"
            dataType: VARCHAR
            defaultValue: ""
            description: ""
            name: LASTPOLICYPERIODS
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"BC_USERSETTINGS\".\"LASTPOLICYPERIODS\""
          - columnReference:
              columnCounter: 2000127362
              stepCounter: "200022876"
            dataType: VARCHAR
            defaultValue: ""
            description: ""
            name: LASTPRODUCERS
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"BC_USERSETTINGS\".\"LASTPRODUCERS\""
          - columnReference:
              columnCounter: 2000127363
              stepCounter: "200022876"
            dataType: NUMBER(38)
            defaultValue: ""
            description: ""
            name: STARTUPPAGE
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"BC_USERSETTINGS\".\"STARTUPPAGE\""
          - columnReference:
              columnCounter: 2000127364
              stepCounter: "200022876"
            dataType: NUMBER(38)
            defaultValue: ""
            description: ""
            name: UPDATEUSERID
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"BC_USERSETTINGS\".\"UPDATEUSERID\""
          - columnReference:
              columnCounter: 2000127365
              stepCounter: "200022876"
            dataType: TIMESTAMP
            defaultValue: ""
            description: ""
            name: UPDATETIME
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"BC_USERSETTINGS\".\"UPDATETIME\""
          - columnReference:
              columnCounter: 2000127366
              stepCounter: "200022876"
            dataType: BOOLEAN
            defaultValue: ""
            description: ""
            name: SHOWPRINTPREVIEW
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"BC_USERSETTINGS\".\"SHOWPRINTPREVIEW\""
          - columnReference:
              columnCounter: 2000127367
              stepCounter: "200022876"
            dataType: NUMBER(2,1)
            defaultValue: ""
            description: ""
            name: PRINTMARGINS
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"BC_USERSETTINGS\".\"PRINTMARGINS\""
          - columnReference:
              columnCounter: 2000127368
              stepCounter: "200022876"
            dataType: NUMBER(38)
            defaultValue: ""
            description: ""
            name: ID
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"BC_USERSETTINGS\".\"ID\""
          - columnReference:
              columnCounter: 2000127369
              stepCounter: "200022876"
            dataType: VARCHAR
            defaultValue: ""
            description: ""
            name: LASTACCOUNTS
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"BC_USERSETTINGS\".\"LASTACCOUNTS\""
          - columnReference:
              columnCounter: 2000127370
              stepCounter: "200022876"
            dataType: VARCHAR
            defaultValue: ""
            description: ""
            name: HVRCAPLOC
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"BC_USERSETTINGS\".\"HVRCAPLOC\""
          - columnReference:
              columnCounter: 2000127371
              stepCounter: "200022876"
            dataType: TIMESTAMP
            defaultValue: ""
            description: ""
            name: HVRCAPTSTAMP
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"BC_USERSETTINGS\".\"HVRCAPTSTAMP\""
          - columnReference:
              columnCounter: 2000127372
              stepCounter: "200022876"
            dataType: TIMESTAMP
            defaultValue: ""
            description: ""
            name: HVRCAPTSTAMPUTC
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"BC_USERSETTINGS\".\"HVRCAPTSTAMPUTC\""
          - columnReference:
              columnCounter: 2000127373
              stepCounter: "200022876"
            dataType: VARCHAR
            defaultValue: ""
            description: ""
            name: HVRCAPUSER
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"BC_USERSETTINGS\".\"HVRCAPUSER\""
          - columnReference:
              columnCounter: 2000127374
              stepCounter: "200022876"
            dataType: VARCHAR
            defaultValue: ""
            description: ""
            name: HVRINTEGKEY
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"BC_USERSETTINGS\".\"HVRINTEGKEY\""
          - columnReference:
              columnCounter: 2000127375
              stepCounter: "200022876"
            dataType: VARCHAR
            defaultValue: ""
            description: ""
            name: HVRINTEGSEQ
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"BC_USERSETTINGS\".\"HVRINTEGSEQ\""
          - columnReference:
              columnCounter: 2000127376
              stepCounter: "200022876"
            dataType: TIMESTAMP
            defaultValue: ""
            description: ""
            name: HVRINTEGTSTAMP
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"BC_USERSETTINGS\".\"HVRINTEGTSTAMP\""
          - columnReference:
              columnCounter: 2000127377
              stepCounter: "200022876"
            dataType: NUMBER(38)
            defaultValue: ""
            description: ""
            name: HVROP
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"BC_USERSETTINGS\".\"HVROP\""
          - columnReference:
              columnCounter: 2000127378
              stepCounter: "200022876"
            dataType: NUMBER(38)
            defaultValue: ""
            description: ""
            name: HVRTXCOUNTDOWN
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"BC_USERSETTINGS\".\"HVRTXCOUNTDOWN\""
          - columnReference:
              columnCounter: 2000127379
              stepCounter: "200022876"
            dataType: VARCHAR
            defaultValue: ""
            description: ""
            name: HVRTXSEQ
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"BC_USERSETTINGS\".\"HVRTXSEQ\""
          - columnReference:
              columnCounter: 2000127351
              stepCounter: "200022876"
            dataType: VARCHAR(256)
            defaultValue: ""
            description: Record source.
            name: DSS_RECORD_SOURCE
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: "'Snowflake_RAW_DB.RAW_GW_BC_PROD.BC_USERSETTINGS'"
          - columnReference:
              columnCounter: 2000127350
              stepCounter: "200022876"
            dataType: TIMESTAMP
            defaultValue: ""
            description: Load date.
            name: DSS_LOAD_DATE
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: CAST(CURRENT_TIMESTAMP AS TIMESTAMP)
        sourceMapping:
          - aliases: {}
            customSQL:
              customSQL: ""
            dependencies:
              - locationName: RAW_GWC_BC_PROD_VF
                nodeName: BC_USERSETTINGS
            join:
              joinCondition: FROM {{ ref('RAW_GWC_BC_PROD_VF','BC_USERSETTINGS') }} "BC_USERSETTINGS" WHERE HVRCAPTSTAMP > (SELECT DATEADD(DAY, -1, NVL(MAX(HVRCAPTSTAMP), '1900-01-01')) FROM {{ ref_no_link('ODS','ODS_GW_BC_PROD_BC_USERSETTINGS') }} "ODS_GW_BC_PROD_BC_USERSETTINGS")
            name: LOAD_GW_BC_PROD_BC_USERSETTINGS
            noLinkRefs:
              - locationName: ODS
                nodeName: ODS_GW_BC_PROD_BC_USERSETTINGS
      name: LOAD_GW_BC_PROD_BC_USERSETTINGS
      overrideSQL: false
      sqlType: "44"
      type: sql
    stepCounter: "200022876"
