steps:
  ODS_GW_BC_PROD_BCX_LOCKBOXWORKERCONFIG_EXT-200023541:
    operation:
      config: {}
      database: ""
      dependencies: []
      deployEnabled: true
      description: ""
      isMultisource: false
      locationID: 20000010
      locationName: ODS
      materializationType: table
      metadata:
        columns:
          - columnReference:
              columnCounter: 2000147081
              stepCounter: "200023541"
            dataType: NUMBER(38)
            defaultValue: ""
            description: ""
            name: LOADCOMMANDID
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"STG_ODS_GW_BC_PROD_BCX_LOCKBOXWORKERCONFIG_EXT_10_NEW\".\"LOADCOMMANDID\""
          - columnReference:
              columnCounter: 2000147082
              stepCounter: "200023541"
            dataType: VARCHAR
            defaultValue: ""
            description: ""
            name: PROCESSUID
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"STG_ODS_GW_BC_PROD_BCX_LOCKBOXWORKERCONFIG_EXT_10_NEW\".\"PROCESSUID\""
          - columnReference:
              columnCounter: 2000147083
              stepCounter: "200023541"
            dataType: NUMBER(38)
            defaultValue: ""
            description: ""
            name: CREATEUSERID
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"STG_ODS_GW_BC_PROD_BCX_LOCKBOXWORKERCONFIG_EXT_10_NEW\".\"CREATEUSERID\""
          - columnReference:
              columnCounter: 2000147084
              stepCounter: "200023541"
            dataType: VARCHAR(64)
            defaultValue: ""
            description: ""
            name: PUBLICID
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"STG_ODS_GW_BC_PROD_BCX_LOCKBOXWORKERCONFIG_EXT_10_NEW\".\"PUBLICID\""
          - columnReference:
              columnCounter: 2000147085
              stepCounter: "200023541"
            dataType: VARCHAR(20)
            defaultValue: ""
            description: ""
            name: BATCHNAME
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"STG_ODS_GW_BC_PROD_BCX_LOCKBOXWORKERCONFIG_EXT_10_NEW\".\"BATCHNAME\""
          - columnReference:
              columnCounter: 2000147086
              stepCounter: "200023541"
            dataType: NUMBER(38)
            defaultValue: ""
            description: ""
            name: NUMBEROFBATCHESPROCESSED
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"STG_ODS_GW_BC_PROD_BCX_LOCKBOXWORKERCONFIG_EXT_10_NEW\".\"NUMBEROFBATCHESPROCESSED\""
          - columnReference:
              columnCounter: 2000147087
              stepCounter: "200023541"
            dataType: TIMESTAMP
            defaultValue: ""
            description: ""
            name: RECEIPTDATE
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"STG_ODS_GW_BC_PROD_BCX_LOCKBOXWORKERCONFIG_EXT_10_NEW\".\"RECEIPTDATE\""
          - columnReference:
              columnCounter: 2000147088
              stepCounter: "200023541"
            dataType: VARCHAR
            defaultValue: ""
            description: ""
            name: MESSAGE
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"STG_ODS_GW_BC_PROD_BCX_LOCKBOXWORKERCONFIG_EXT_10_NEW\".\"MESSAGE\""
          - columnReference:
              columnCounter: 2000147089
              stepCounter: "200023541"
            dataType: NUMBER(38)
            defaultValue: ""
            description: ""
            name: BEANVERSION
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"STG_ODS_GW_BC_PROD_BCX_LOCKBOXWORKERCONFIG_EXT_10_NEW\".\"BEANVERSION\""
          - columnReference:
              columnCounter: 2000147090
              stepCounter: "200023541"
            dataType: TIMESTAMP
            defaultValue: ""
            description: ""
            name: CREATETIME
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"STG_ODS_GW_BC_PROD_BCX_LOCKBOXWORKERCONFIG_EXT_10_NEW\".\"CREATETIME\""
          - columnReference:
              columnCounter: 2000147091
              stepCounter: "200023541"
            dataType: NUMBER(38)
            defaultValue: ""
            description: ""
            name: RETIRED
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"STG_ODS_GW_BC_PROD_BCX_LOCKBOXWORKERCONFIG_EXT_10_NEW\".\"RETIRED\""
          - columnReference:
              columnCounter: 2000147092
              stepCounter: "200023541"
            dataType: NUMBER(38)
            defaultValue: ""
            description: ""
            name: NUMBEROFRECORDSPROCESSED
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"STG_ODS_GW_BC_PROD_BCX_LOCKBOXWORKERCONFIG_EXT_10_NEW\".\"NUMBEROFRECORDSPROCESSED\""
          - columnReference:
              columnCounter: 2000147093
              stepCounter: "200023541"
            dataType: NUMBER(18,2)
            defaultValue: ""
            description: ""
            name: TOTALAMOUNTFORBATCH
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"STG_ODS_GW_BC_PROD_BCX_LOCKBOXWORKERCONFIG_EXT_10_NEW\".\"TOTALAMOUNTFORBATCH\""
          - columnReference:
              columnCounter: 2000147094
              stepCounter: "200023541"
            dataType: NUMBER(38)
            defaultValue: ""
            description: ""
            name: UPDATEUSERID
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"STG_ODS_GW_BC_PROD_BCX_LOCKBOXWORKERCONFIG_EXT_10_NEW\".\"UPDATEUSERID\""
          - columnReference:
              columnCounter: 2000147095
              stepCounter: "200023541"
            dataType: NUMBER(38)
            defaultValue: ""
            description: ""
            name: STARTINDEX
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"STG_ODS_GW_BC_PROD_BCX_LOCKBOXWORKERCONFIG_EXT_10_NEW\".\"STARTINDEX\""
          - columnReference:
              columnCounter: 2000147096
              stepCounter: "200023541"
            dataType: NUMBER(38)
            defaultValue: ""
            description: ""
            name: STATUS
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"STG_ODS_GW_BC_PROD_BCX_LOCKBOXWORKERCONFIG_EXT_10_NEW\".\"STATUS\""
          - columnReference:
              columnCounter: 2000147097
              stepCounter: "200023541"
            dataType: TIMESTAMP
            defaultValue: ""
            description: ""
            name: UPDATETIME
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"STG_ODS_GW_BC_PROD_BCX_LOCKBOXWORKERCONFIG_EXT_10_NEW\".\"UPDATETIME\""
          - columnReference:
              columnCounter: 2000147098
              stepCounter: "200023541"
            dataType: NUMBER(38)
            defaultValue: ""
            description: ""
            name: ENDINDEX
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"STG_ODS_GW_BC_PROD_BCX_LOCKBOXWORKERCONFIG_EXT_10_NEW\".\"ENDINDEX\""
          - columnReference:
              columnCounter: 2000147099
              stepCounter: "200023541"
            dataType: NUMBER(38)
            defaultValue: ""
            description: ""
            name: ID
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"STG_ODS_GW_BC_PROD_BCX_LOCKBOXWORKERCONFIG_EXT_10_NEW\".\"ID\""
          - columnReference:
              columnCounter: 2000147100
              stepCounter: "200023541"
            dataType: NUMBER(38)
            defaultValue: ""
            description: ""
            name: BATCHSEQUENCE
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"STG_ODS_GW_BC_PROD_BCX_LOCKBOXWORKERCONFIG_EXT_10_NEW\".\"BATCHSEQUENCE\""
          - columnReference:
              columnCounter: 2000147101
              stepCounter: "200023541"
            dataType: NUMBER(38)
            defaultValue: ""
            description: ""
            name: NUMBEROFPAYMENTSCREATED
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"STG_ODS_GW_BC_PROD_BCX_LOCKBOXWORKERCONFIG_EXT_10_NEW\".\"NUMBEROFPAYMENTSCREATED\""
          - columnReference:
              columnCounter: 2000147102
              stepCounter: "200023541"
            dataType: VARCHAR(60)
            defaultValue: ""
            description: ""
            name: BATCHRUNUID
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"STG_ODS_GW_BC_PROD_BCX_LOCKBOXWORKERCONFIG_EXT_10_NEW\".\"BATCHRUNUID\""
          - columnReference:
              columnCounter: 2000147103
              stepCounter: "200023541"
            dataType: VARCHAR
            defaultValue: ""
            description: ""
            name: HVRCAPLOC
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"STG_ODS_GW_BC_PROD_BCX_LOCKBOXWORKERCONFIG_EXT_10_NEW\".\"HVRCAPLOC\""
          - columnReference:
              columnCounter: 2000147104
              stepCounter: "200023541"
            dataType: TIMESTAMP
            defaultValue: ""
            description: ""
            name: HVRCAPTSTAMP
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"STG_ODS_GW_BC_PROD_BCX_LOCKBOXWORKERCONFIG_EXT_10_NEW\".\"HVRCAPTSTAMP\""
          - columnReference:
              columnCounter: 2000147105
              stepCounter: "200023541"
            dataType: TIMESTAMP
            defaultValue: ""
            description: ""
            name: HVRCAPTSTAMPUTC
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"STG_ODS_GW_BC_PROD_BCX_LOCKBOXWORKERCONFIG_EXT_10_NEW\".\"HVRCAPTSTAMPUTC\""
          - columnReference:
              columnCounter: 2000147106
              stepCounter: "200023541"
            dataType: VARCHAR(50)
            defaultValue: ""
            description: ""
            name: HVRCAPTUREKEY
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"STG_ODS_GW_BC_PROD_BCX_LOCKBOXWORKERCONFIG_EXT_10_NEW\".\"HVRCAPTUREKEY\""
          - columnReference:
              columnCounter: 2000147107
              stepCounter: "200023541"
            dataType: NUMBER
            defaultValue: ""
            description: Historical Refresh SEQNO for the HVR Table within the specified window
            isBusinessKey: "true"
            name: HVR_REFRESH_SEQNO
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"STG_ODS_GW_BC_PROD_BCX_LOCKBOXWORKERCONFIG_EXT_10_NEW\".\"HVR_REFRESH_SEQNO\""
          - columnReference:
              columnCounter: 2000147108
              stepCounter: "200023541"
            dataType: VARCHAR(15)
            defaultValue: ""
            description: Batch Number for the Process Cycle
            name: BATCH_NUMBER
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"STG_ODS_GW_BC_PROD_BCX_LOCKBOXWORKERCONFIG_EXT_10_NEW\".\"BATCH_NUMBER\""
          - columnReference:
              columnCounter: 2000147109
              stepCounter: "200023541"
            dataType: VARCHAR
            defaultValue: ""
            description: ""
            name: HVRCAPUSER
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"STG_ODS_GW_BC_PROD_BCX_LOCKBOXWORKERCONFIG_EXT_10_NEW\".\"HVRCAPUSER\""
          - columnReference:
              columnCounter: 2000147110
              stepCounter: "200023541"
            dataType: VARCHAR
            defaultValue: ""
            description: ""
            name: HVRINTEGKEY
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"STG_ODS_GW_BC_PROD_BCX_LOCKBOXWORKERCONFIG_EXT_10_NEW\".\"HVRINTEGKEY\""
          - columnReference:
              columnCounter: 2000147111
              stepCounter: "200023541"
            dataType: VARCHAR
            defaultValue: ""
            description: ""
            isBusinessKey: "true"
            name: HVRINTEGSEQ
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"STG_ODS_GW_BC_PROD_BCX_LOCKBOXWORKERCONFIG_EXT_10_NEW\".\"HVRINTEGSEQ\""
          - columnReference:
              columnCounter: 2000147112
              stepCounter: "200023541"
            dataType: TIMESTAMP
            defaultValue: ""
            description: ""
            name: HVRINTEGTSTAMP
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"STG_ODS_GW_BC_PROD_BCX_LOCKBOXWORKERCONFIG_EXT_10_NEW\".\"HVRINTEGTSTAMP\""
          - columnReference:
              columnCounter: 2000147113
              stepCounter: "200023541"
            dataType: NUMBER(38)
            defaultValue: ""
            description: ""
            name: HVROP
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"STG_ODS_GW_BC_PROD_BCX_LOCKBOXWORKERCONFIG_EXT_10_NEW\".\"HVROP\""
          - columnReference:
              columnCounter: 2000147114
              stepCounter: "200023541"
            dataType: NUMBER(38)
            defaultValue: ""
            description: ""
            name: HVRTXCOUNTDOWN
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"STG_ODS_GW_BC_PROD_BCX_LOCKBOXWORKERCONFIG_EXT_10_NEW\".\"HVRTXCOUNTDOWN\""
          - columnReference:
              columnCounter: 2000147115
              stepCounter: "200023541"
            dataType: VARCHAR
            defaultValue: ""
            description: ""
            name: HVRTXSEQ
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"STG_ODS_GW_BC_PROD_BCX_LOCKBOXWORKERCONFIG_EXT_10_NEW\".\"HVRTXSEQ\""
          - columnReference:
              columnCounter: 2000147116
              stepCounter: "200023541"
            dataType: VARCHAR(256)
            defaultValue: ""
            description: Record source.
            name: DSS_RECORD_SOURCE
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"STG_ODS_GW_BC_PROD_BCX_LOCKBOXWORKERCONFIG_EXT_10_NEW\".\"DSS_RECORD_SOURCE\""
          - columnReference:
              columnCounter: 2000147117
              stepCounter: "200023541"
            dataType: TIMESTAMP
            defaultValue: ""
            description: Load date.
            name: DSS_LOAD_DATE
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"STG_ODS_GW_BC_PROD_BCX_LOCKBOXWORKERCONFIG_EXT_10_NEW\".\"DSS_LOAD_DATE\""
          - columnReference:
              columnCounter: 2000147119
              stepCounter: "200023541"
            dataType: TIMESTAMP
            defaultValue: ""
            description: Date and time the row was created in the data warehouse.
            name: DSS_CREATE_TIME
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: CAST(CURRENT_TIMESTAMP AS TIMESTAMP)
          - columnReference:
              columnCounter: 2000147118
              stepCounter: "200023541"
            dataType: TIMESTAMP
            defaultValue: ""
            description: Date and time the row was updated in the data warehouse.
            name: DSS_UPDATE_TIME
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: CAST(CURRENT_TIMESTAMP AS TIMESTAMP)
        sourceMapping:
          - aliases: {}
            customSQL:
              customSQL: ""
            dependencies:
              - locationName: STAGE
                nodeName: STG_ODS_GW_BC_PROD_BCX_LOCKBOXWORKERCONFIG_EXT_10_NEW
            join:
              joinCondition: FROM {{ ref('STAGE','STG_ODS_GW_BC_PROD_BCX_LOCKBOXWORKERCONFIG_EXT_10_NEW') }} "STG_ODS_GW_BC_PROD_BCX_LOCKBOXWORKERCONFIG_EXT_10_NEW"
            name: ODS_GW_BC_PROD_BCX_LOCKBOXWORKERCONFIG_EXT
            noLinkRefs: []
      name: ODS_GW_BC_PROD_BCX_LOCKBOXWORKERCONFIG_EXT
      overrideSQL: false
      sqlType: "10"
      type: sql
    stepCounter: "200023541"
