steps:
  ODS_GW_BC_PROD_BC_USERSETTINGS-200023121:
    operation:
      config: {}
      database: ""
      dependencies: []
      deployEnabled: true
      description: ""
      isMultisource: false
      locationID: 20000010
      locationName: ODS
      materializationType: table
      metadata:
        columns:
          - columnReference:
              columnCounter: 2000146078
              stepCounter: "200023121"
            dataType: BOOLEAN
            defaultValue: ""
            description: ""
            name: ROTATETABLES
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"STG_ODS_GW_BC_PROD_BC_USERSETTINGS_10_NEW\".\"ROTATETABLES\""
          - columnReference:
              columnCounter: 2000146079
              stepCounter: "200023121"
            dataType: NUMBER(38)
            defaultValue: ""
            description: ""
            name: LOADCOMMANDID
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"STG_ODS_GW_BC_PROD_BC_USERSETTINGS_10_NEW\".\"LOADCOMMANDID\""
          - columnReference:
              columnCounter: 2000146080
              stepCounter: "200023121"
            dataType: NUMBER(38)
            defaultValue: ""
            description: ""
            name: CREATEUSERID
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"STG_ODS_GW_BC_PROD_BC_USERSETTINGS_10_NEW\".\"CREATEUSERID\""
          - columnReference:
              columnCounter: 2000146081
              stepCounter: "200023121"
            dataType: VARCHAR(64)
            defaultValue: ""
            description: ""
            name: PUBLICID
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"STG_ODS_GW_BC_PROD_BC_USERSETTINGS_10_NEW\".\"PUBLICID\""
          - columnReference:
              columnCounter: 2000146082
              stepCounter: "200023121"
            dataType: NUMBER(38)
            defaultValue: ""
            description: ""
            name: BEANVERSION
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"STG_ODS_GW_BC_PROD_BC_USERSETTINGS_10_NEW\".\"BEANVERSION\""
          - columnReference:
              columnCounter: 2000146083
              stepCounter: "200023121"
            dataType: TIMESTAMP
            defaultValue: ""
            description: ""
            name: CANCELALERTDISMISS
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"STG_ODS_GW_BC_PROD_BC_USERSETTINGS_10_NEW\".\"CANCELALERTDISMISS\""
          - columnReference:
              columnCounter: 2000146084
              stepCounter: "200023121"
            dataType: BOOLEAN
            defaultValue: ""
            description: ""
            name: PRINTPAGENUMS
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"STG_ODS_GW_BC_PROD_BC_USERSETTINGS_10_NEW\".\"PRINTPAGENUMS\""
          - columnReference:
              columnCounter: 2000146085
              stepCounter: "200023121"
            dataType: NUMBER(38)
            defaultValue: ""
            description: ""
            name: RETIRED
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"STG_ODS_GW_BC_PROD_BC_USERSETTINGS_10_NEW\".\"RETIRED\""
          - columnReference:
              columnCounter: 2000146086
              stepCounter: "200023121"
            dataType: TIMESTAMP
            defaultValue: ""
            description: ""
            name: CREATETIME
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"STG_ODS_GW_BC_PROD_BC_USERSETTINGS_10_NEW\".\"CREATETIME\""
          - columnReference:
              columnCounter: 2000146087
              stepCounter: "200023121"
            dataType: VARCHAR
            defaultValue: ""
            description: ""
            name: LASTPOLICYPERIODS
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"STG_ODS_GW_BC_PROD_BC_USERSETTINGS_10_NEW\".\"LASTPOLICYPERIODS\""
          - columnReference:
              columnCounter: 2000146088
              stepCounter: "200023121"
            dataType: VARCHAR
            defaultValue: ""
            description: ""
            name: LASTPRODUCERS
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"STG_ODS_GW_BC_PROD_BC_USERSETTINGS_10_NEW\".\"LASTPRODUCERS\""
          - columnReference:
              columnCounter: 2000146089
              stepCounter: "200023121"
            dataType: NUMBER(38)
            defaultValue: ""
            description: ""
            name: STARTUPPAGE
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"STG_ODS_GW_BC_PROD_BC_USERSETTINGS_10_NEW\".\"STARTUPPAGE\""
          - columnReference:
              columnCounter: 2000146090
              stepCounter: "200023121"
            dataType: NUMBER(38)
            defaultValue: ""
            description: ""
            name: UPDATEUSERID
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"STG_ODS_GW_BC_PROD_BC_USERSETTINGS_10_NEW\".\"UPDATEUSERID\""
          - columnReference:
              columnCounter: 2000146091
              stepCounter: "200023121"
            dataType: TIMESTAMP
            defaultValue: ""
            description: ""
            name: UPDATETIME
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"STG_ODS_GW_BC_PROD_BC_USERSETTINGS_10_NEW\".\"UPDATETIME\""
          - columnReference:
              columnCounter: 2000146092
              stepCounter: "200023121"
            dataType: BOOLEAN
            defaultValue: ""
            description: ""
            name: SHOWPRINTPREVIEW
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"STG_ODS_GW_BC_PROD_BC_USERSETTINGS_10_NEW\".\"SHOWPRINTPREVIEW\""
          - columnReference:
              columnCounter: 2000146093
              stepCounter: "200023121"
            dataType: NUMBER(2,1)
            defaultValue: ""
            description: ""
            name: PRINTMARGINS
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"STG_ODS_GW_BC_PROD_BC_USERSETTINGS_10_NEW\".\"PRINTMARGINS\""
          - columnReference:
              columnCounter: 2000146094
              stepCounter: "200023121"
            dataType: NUMBER(38)
            defaultValue: ""
            description: ""
            name: ID
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"STG_ODS_GW_BC_PROD_BC_USERSETTINGS_10_NEW\".\"ID\""
          - columnReference:
              columnCounter: 2000146095
              stepCounter: "200023121"
            dataType: VARCHAR
            defaultValue: ""
            description: ""
            name: LASTACCOUNTS
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"STG_ODS_GW_BC_PROD_BC_USERSETTINGS_10_NEW\".\"LASTACCOUNTS\""
          - columnReference:
              columnCounter: 2000146096
              stepCounter: "200023121"
            dataType: VARCHAR
            defaultValue: ""
            description: ""
            name: HVRCAPLOC
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"STG_ODS_GW_BC_PROD_BC_USERSETTINGS_10_NEW\".\"HVRCAPLOC\""
          - columnReference:
              columnCounter: 2000146097
              stepCounter: "200023121"
            dataType: TIMESTAMP
            defaultValue: ""
            description: ""
            name: HVRCAPTSTAMP
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"STG_ODS_GW_BC_PROD_BC_USERSETTINGS_10_NEW\".\"HVRCAPTSTAMP\""
          - columnReference:
              columnCounter: 2000146098
              stepCounter: "200023121"
            dataType: TIMESTAMP
            defaultValue: ""
            description: ""
            name: HVRCAPTSTAMPUTC
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"STG_ODS_GW_BC_PROD_BC_USERSETTINGS_10_NEW\".\"HVRCAPTSTAMPUTC\""
          - columnReference:
              columnCounter: 2000146099
              stepCounter: "200023121"
            dataType: VARCHAR(50)
            defaultValue: ""
            description: ""
            name: HVRCAPTUREKEY
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"STG_ODS_GW_BC_PROD_BC_USERSETTINGS_10_NEW\".\"HVRCAPTUREKEY\""
          - columnReference:
              columnCounter: 2000146100
              stepCounter: "200023121"
            dataType: NUMBER
            defaultValue: ""
            description: Historical Refresh SEQNO for the HVR Table within the specified window
            isBusinessKey: "true"
            name: HVR_REFRESH_SEQNO
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"STG_ODS_GW_BC_PROD_BC_USERSETTINGS_10_NEW\".\"HVR_REFRESH_SEQNO\""
          - columnReference:
              columnCounter: 2000146101
              stepCounter: "200023121"
            dataType: VARCHAR(15)
            defaultValue: ""
            description: Batch Number for the Process Cycle
            name: BATCH_NUMBER
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"STG_ODS_GW_BC_PROD_BC_USERSETTINGS_10_NEW\".\"BATCH_NUMBER\""
          - columnReference:
              columnCounter: 2000146102
              stepCounter: "200023121"
            dataType: VARCHAR
            defaultValue: ""
            description: ""
            name: HVRCAPUSER
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"STG_ODS_GW_BC_PROD_BC_USERSETTINGS_10_NEW\".\"HVRCAPUSER\""
          - columnReference:
              columnCounter: 2000146103
              stepCounter: "200023121"
            dataType: VARCHAR
            defaultValue: ""
            description: ""
            name: HVRINTEGKEY
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"STG_ODS_GW_BC_PROD_BC_USERSETTINGS_10_NEW\".\"HVRINTEGKEY\""
          - columnReference:
              columnCounter: 2000146104
              stepCounter: "200023121"
            dataType: VARCHAR
            defaultValue: ""
            description: ""
            isBusinessKey: "true"
            name: HVRINTEGSEQ
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"STG_ODS_GW_BC_PROD_BC_USERSETTINGS_10_NEW\".\"HVRINTEGSEQ\""
          - columnReference:
              columnCounter: 2000146105
              stepCounter: "200023121"
            dataType: TIMESTAMP
            defaultValue: ""
            description: ""
            name: HVRINTEGTSTAMP
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"STG_ODS_GW_BC_PROD_BC_USERSETTINGS_10_NEW\".\"HVRINTEGTSTAMP\""
          - columnReference:
              columnCounter: 2000146106
              stepCounter: "200023121"
            dataType: NUMBER(38)
            defaultValue: ""
            description: ""
            name: HVROP
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"STG_ODS_GW_BC_PROD_BC_USERSETTINGS_10_NEW\".\"HVROP\""
          - columnReference:
              columnCounter: 2000146107
              stepCounter: "200023121"
            dataType: NUMBER(38)
            defaultValue: ""
            description: ""
            name: HVRTXCOUNTDOWN
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"STG_ODS_GW_BC_PROD_BC_USERSETTINGS_10_NEW\".\"HVRTXCOUNTDOWN\""
          - columnReference:
              columnCounter: 2000146108
              stepCounter: "200023121"
            dataType: VARCHAR
            defaultValue: ""
            description: ""
            name: HVRTXSEQ
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"STG_ODS_GW_BC_PROD_BC_USERSETTINGS_10_NEW\".\"HVRTXSEQ\""
          - columnReference:
              columnCounter: 2000146109
              stepCounter: "200023121"
            dataType: VARCHAR(256)
            defaultValue: ""
            description: Record source.
            name: DSS_RECORD_SOURCE
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"STG_ODS_GW_BC_PROD_BC_USERSETTINGS_10_NEW\".\"DSS_RECORD_SOURCE\""
          - columnReference:
              columnCounter: 2000146110
              stepCounter: "200023121"
            dataType: TIMESTAMP
            defaultValue: ""
            description: Load date.
            name: DSS_LOAD_DATE
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"STG_ODS_GW_BC_PROD_BC_USERSETTINGS_10_NEW\".\"DSS_LOAD_DATE\""
          - columnReference:
              columnCounter: 2000146112
              stepCounter: "200023121"
            dataType: TIMESTAMP
            defaultValue: ""
            description: Date and time the row was created in the data warehouse.
            name: DSS_CREATE_TIME
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: CAST(CURRENT_TIMESTAMP AS TIMESTAMP)
          - columnReference:
              columnCounter: 2000146111
              stepCounter: "200023121"
            dataType: TIMESTAMP
            defaultValue: ""
            description: Date and time the row was updated in the data warehouse.
            name: DSS_UPDATE_TIME
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: CAST(CURRENT_TIMESTAMP AS TIMESTAMP)
        sourceMapping:
          - aliases: {}
            customSQL:
              customSQL: ""
            dependencies:
              - locationName: STAGE
                nodeName: STG_ODS_GW_BC_PROD_BC_USERSETTINGS_10_NEW
            join:
              joinCondition: FROM {{ ref('STAGE','STG_ODS_GW_BC_PROD_BC_USERSETTINGS_10_NEW') }} "STG_ODS_GW_BC_PROD_BC_USERSETTINGS_10_NEW"
            name: ODS_GW_BC_PROD_BC_USERSETTINGS
            noLinkRefs: []
      name: ODS_GW_BC_PROD_BC_USERSETTINGS
      overrideSQL: false
      sqlType: "10"
      type: sql
    stepCounter: "200023121"
