steps:
  BC_OUTBOUNDFILECONFIG-10138:
    operation:
      database: ""
      dataset: ""
      deployEnabled: true
      description: ""
      locationID: ""
      locationName: RAW_GWC_BC_PROD_VF
      metadata:
        columns:
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 413200
              stepCounter: 10138
            config: {}
            dataType: NUMBER(38,0)
            defaultValue: ""
            description: ""
            name: BEANVERSION
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 413201
              stepCounter: 10138
            config: {}
            dataType: TIMESTAMP_NTZ(9)
            defaultValue: ""
            description: ""
            name: CREATETIME
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 413202
              stepCounter: 10138
            config: {}
            dataType: NUMBER(38,0)
            defaultValue: ""
            description: ""
            name: CREATEUSERID
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 413203
              stepCounter: 10138
            config: {}
            dataType: NUMBER(38,0)
            defaultValue: ""
            description: ""
            name: DAYSTILLPURGE
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 413204
              stepCounter: 10138
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: DESTINATIONS3BUCKET
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 413205
              stepCounter: 10138
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: DESTINATIONS3PREFIX
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 413206
              stepCounter: 10138
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: EXTENSION
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 413207
              stepCounter: 10138
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: FILEHANDLERCLASS
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 413208
              stepCounter: 10138
            config: {}
            dataType: NUMBER(38,0)
            defaultValue: ""
            description: ""
            name: GWCBI___SEQVAL
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 413209
              stepCounter: 10138
            config: {}
            dataType: NUMBER(38,0)
            defaultValue: ""
            description: ""
            name: ID
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 413210
              stepCounter: 10138
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: NAME
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 413211
              stepCounter: 10138
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: PERMANENTDIRECTORY
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 413212
              stepCounter: 10138
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: PREFIX
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 413213
              stepCounter: 10138
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: PROFILENAME
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 413214
              stepCounter: 10138
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: PUBLICID
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 413215
              stepCounter: 10138
            config: {}
            dataType: NUMBER(38,0)
            defaultValue: ""
            description: ""
            name: SUBTYPE
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 413216
              stepCounter: 10138
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: TEMPORARYDIRECTORY
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 413217
              stepCounter: 10138
            config: {}
            dataType: TIMESTAMP_NTZ(9)
            defaultValue: ""
            description: ""
            name: UPDATETIME
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 413218
              stepCounter: 10138
            config: {}
            dataType: NUMBER(38,0)
            defaultValue: ""
            description: ""
            name: UPDATEUSERID
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 413219
              stepCounter: 10138
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: HVRCAPLOC
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 413220
              stepCounter: 10138
            config: {}
            dataType: TIMESTAMP_LTZ(9)
            defaultValue: ""
            description: ""
            name: HVRCAPTSTAMP
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 413221
              stepCounter: 10138
            config: {}
            dataType: TIMESTAMP_NTZ(9)
            defaultValue: ""
            description: ""
            name: HVRCAPTSTAMPUTC
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 413222
              stepCounter: 10138
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: HVRCAPUSER
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 413223
              stepCounter: 10138
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: HVRINTEGKEY
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 413224
              stepCounter: 10138
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: HVRINTEGSEQ
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 413225
              stepCounter: 10138
            config: {}
            dataType: TIMESTAMP_LTZ(9)
            defaultValue: ""
            description: ""
            name: HVRINTEGTSTAMP
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 413226
              stepCounter: 10138
            config: {}
            dataType: NUMBER(38,0)
            defaultValue: ""
            description: ""
            name: HVROP
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 413227
              stepCounter: 10138
            config: {}
            dataType: NUMBER(38,0)
            defaultValue: ""
            description: ""
            name: HVRTXCOUNTDOWN
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 413228
              stepCounter: 10138
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: HVRTXSEQ
            nullable: true
            primaryKey: false
            uniqueKey: false
        join:
          joinCondition: FROM {{ ref('RAW_GWC_BC_PROD_VF', 'BC_OUTBOUNDFILECONFIG') }}
      name: BC_OUTBOUNDFILECONFIG
      schema: ""
      sqlType: Source
      table: BC_OUTBOUNDFILECONFIG
      type: sourceInput
    stepCounter: "10138"
