steps:
  STG_ODS_GW_BC_PROD_BCX_LOCKBOXWORKERCONFIG_EXT_10_NEW-200023538:
    operation:
      config:
        insertStrategy: INSERT
        postSQL: ""
        preSQL: ""
        testsEnabled: true
        truncateBefore: true
      database: ""
      dependencies: []
      deployEnabled: true
      description: ""
      isMultisource: false
      locationID: 20000002
      locationName: STAGE
      materializationType: table
      metadata:
        columns:
          - columnReference:
              columnCounter: 2000252373
              stepCounter: "200023538"
            dataType: NUMBER(38)
            defaultValue: ""
            description: ""
            name: LOADCOMMANDID
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"LOAD_GW_BC_PROD_BCX_LOCKBOXWORKERCONFIG_EXT\".\"LOADCOMMANDID\""
          - columnReference:
              columnCounter: 2000252374
              stepCounter: "200023538"
            dataType: VARCHAR
            defaultValue: ""
            description: ""
            name: PROCESSUID
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"LOAD_GW_BC_PROD_BCX_LOCKBOXWORKERCONFIG_EXT\".\"PROCESSUID\""
          - columnReference:
              columnCounter: 2000252375
              stepCounter: "200023538"
            dataType: NUMBER(38)
            defaultValue: ""
            description: ""
            name: CREATEUSERID
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"LOAD_GW_BC_PROD_BCX_LOCKBOXWORKERCONFIG_EXT\".\"CREATEUSERID\""
          - columnReference:
              columnCounter: 2000252376
              stepCounter: "200023538"
            dataType: VARCHAR(64)
            defaultValue: ""
            description: ""
            name: PUBLICID
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"LOAD_GW_BC_PROD_BCX_LOCKBOXWORKERCONFIG_EXT\".\"PUBLICID\""
          - columnReference:
              columnCounter: 2000252377
              stepCounter: "200023538"
            dataType: VARCHAR(20)
            defaultValue: ""
            description: ""
            name: BATCHNAME
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"LOAD_GW_BC_PROD_BCX_LOCKBOXWORKERCONFIG_EXT\".\"BATCHNAME\""
          - columnReference:
              columnCounter: 2000252378
              stepCounter: "200023538"
            dataType: NUMBER(38)
            defaultValue: ""
            description: ""
            name: NUMBEROFBATCHESPROCESSED
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"LOAD_GW_BC_PROD_BCX_LOCKBOXWORKERCONFIG_EXT\".\"NUMBEROFBATCHESPROCESSED\""
          - columnReference:
              columnCounter: 2000252379
              stepCounter: "200023538"
            dataType: TIMESTAMP
            defaultValue: ""
            description: ""
            name: RECEIPTDATE
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"LOAD_GW_BC_PROD_BCX_LOCKBOXWORKERCONFIG_EXT\".\"RECEIPTDATE\""
          - columnReference:
              columnCounter: 2000252380
              stepCounter: "200023538"
            dataType: VARCHAR
            defaultValue: ""
            description: ""
            name: MESSAGE
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"LOAD_GW_BC_PROD_BCX_LOCKBOXWORKERCONFIG_EXT\".\"MESSAGE\""
          - columnReference:
              columnCounter: 2000252381
              stepCounter: "200023538"
            dataType: NUMBER(38)
            defaultValue: ""
            description: ""
            name: BEANVERSION
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"LOAD_GW_BC_PROD_BCX_LOCKBOXWORKERCONFIG_EXT\".\"BEANVERSION\""
          - columnReference:
              columnCounter: 2000252382
              stepCounter: "200023538"
            dataType: TIMESTAMP
            defaultValue: ""
            description: ""
            name: CREATETIME
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"LOAD_GW_BC_PROD_BCX_LOCKBOXWORKERCONFIG_EXT\".\"CREATETIME\""
          - columnReference:
              columnCounter: 2000252383
              stepCounter: "200023538"
            dataType: NUMBER(38)
            defaultValue: ""
            description: ""
            name: RETIRED
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"LOAD_GW_BC_PROD_BCX_LOCKBOXWORKERCONFIG_EXT\".\"RETIRED\""
          - columnReference:
              columnCounter: 2000252384
              stepCounter: "200023538"
            dataType: NUMBER(38)
            defaultValue: ""
            description: ""
            name: NUMBEROFRECORDSPROCESSED
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"LOAD_GW_BC_PROD_BCX_LOCKBOXWORKERCONFIG_EXT\".\"NUMBEROFRECORDSPROCESSED\""
          - columnReference:
              columnCounter: 2000252385
              stepCounter: "200023538"
            dataType: NUMBER(18,2)
            defaultValue: ""
            description: ""
            name: TOTALAMOUNTFORBATCH
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"LOAD_GW_BC_PROD_BCX_LOCKBOXWORKERCONFIG_EXT\".\"TOTALAMOUNTFORBATCH\""
          - columnReference:
              columnCounter: 2000252386
              stepCounter: "200023538"
            dataType: NUMBER(38)
            defaultValue: ""
            description: ""
            name: UPDATEUSERID
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"LOAD_GW_BC_PROD_BCX_LOCKBOXWORKERCONFIG_EXT\".\"UPDATEUSERID\""
          - columnReference:
              columnCounter: 2000252387
              stepCounter: "200023538"
            dataType: NUMBER(38)
            defaultValue: ""
            description: ""
            name: STARTINDEX
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"LOAD_GW_BC_PROD_BCX_LOCKBOXWORKERCONFIG_EXT\".\"STARTINDEX\""
          - columnReference:
              columnCounter: 2000252388
              stepCounter: "200023538"
            dataType: NUMBER(38)
            defaultValue: ""
            description: ""
            name: STATUS
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"LOAD_GW_BC_PROD_BCX_LOCKBOXWORKERCONFIG_EXT\".\"STATUS\""
          - columnReference:
              columnCounter: 2000252389
              stepCounter: "200023538"
            dataType: TIMESTAMP
            defaultValue: ""
            description: ""
            name: UPDATETIME
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"LOAD_GW_BC_PROD_BCX_LOCKBOXWORKERCONFIG_EXT\".\"UPDATETIME\""
          - columnReference:
              columnCounter: 2000252390
              stepCounter: "200023538"
            dataType: NUMBER(38)
            defaultValue: ""
            description: ""
            name: ENDINDEX
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"LOAD_GW_BC_PROD_BCX_LOCKBOXWORKERCONFIG_EXT\".\"ENDINDEX\""
          - columnReference:
              columnCounter: 2000252391
              stepCounter: "200023538"
            dataType: NUMBER(38)
            defaultValue: ""
            description: ""
            name: ID
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"LOAD_GW_BC_PROD_BCX_LOCKBOXWORKERCONFIG_EXT\".\"ID\""
          - columnReference:
              columnCounter: 2000252392
              stepCounter: "200023538"
            dataType: NUMBER(38)
            defaultValue: ""
            description: ""
            name: BATCHSEQUENCE
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"LOAD_GW_BC_PROD_BCX_LOCKBOXWORKERCONFIG_EXT\".\"BATCHSEQUENCE\""
          - columnReference:
              columnCounter: 2000252393
              stepCounter: "200023538"
            dataType: NUMBER(38)
            defaultValue: ""
            description: ""
            name: NUMBEROFPAYMENTSCREATED
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"LOAD_GW_BC_PROD_BCX_LOCKBOXWORKERCONFIG_EXT\".\"NUMBEROFPAYMENTSCREATED\""
          - columnReference:
              columnCounter: 2000252394
              stepCounter: "200023538"
            dataType: VARCHAR(60)
            defaultValue: ""
            description: ""
            name: BATCHRUNUID
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"LOAD_GW_BC_PROD_BCX_LOCKBOXWORKERCONFIG_EXT\".\"BATCHRUNUID\""
          - columnReference:
              columnCounter: 2000252395
              stepCounter: "200023538"
            dataType: VARCHAR
            defaultValue: ""
            description: ""
            name: HVRCAPLOC
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"LOAD_GW_BC_PROD_BCX_LOCKBOXWORKERCONFIG_EXT\".\"HVRCAPLOC\""
          - columnReference:
              columnCounter: 2000252396
              stepCounter: "200023538"
            dataType: TIMESTAMP
            defaultValue: ""
            description: ""
            name: HVRCAPTSTAMP
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"LOAD_GW_BC_PROD_BCX_LOCKBOXWORKERCONFIG_EXT\".\"HVRCAPTSTAMP\""
          - columnReference:
              columnCounter: 2000252397
              stepCounter: "200023538"
            dataType: TIMESTAMP
            defaultValue: ""
            description: ""
            name: HVRCAPTSTAMPUTC
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"LOAD_GW_BC_PROD_BCX_LOCKBOXWORKERCONFIG_EXT\".\"HVRCAPTSTAMPUTC\""
          - columnReference:
              columnCounter: 2000252409
              stepCounter: "200023538"
            dataType: VARCHAR(50)
            defaultValue: ""
            description: ""
            name: HVRCAPTUREKEY
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"STG_ODS_GW_BC_PROD_BCX_LOCKBOXWORKERCONFIG_EXT_05_SEQNO\".\"HVRCAPTUREKEY\""
          - columnReference:
              columnCounter: 2000252410
              stepCounter: "200023538"
            dataType: NUMBER
            defaultValue: ""
            description: Historical Refresh SEQNO for the HVR Table within the specified window
            name: HVR_REFRESH_SEQNO
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"STG_ODS_GW_BC_PROD_BCX_LOCKBOXWORKERCONFIG_EXT_05_SEQNO\".\"HVR_REFRESH_SEQNO\""
          - columnReference:
              columnCounter: 2000252411
              stepCounter: "200023538"
            dataType: VARCHAR(15)
            defaultValue: ""
            description: Batch Number for the Process Cycle
            name: BATCH_NUMBER
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"ODS_CTRL_HVRCAPTSTAMP\".\"BATCH_NUMBER\""
          - columnReference:
              columnCounter: 2000252398
              stepCounter: "200023538"
            dataType: VARCHAR
            defaultValue: ""
            description: ""
            name: HVRCAPUSER
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"LOAD_GW_BC_PROD_BCX_LOCKBOXWORKERCONFIG_EXT\".\"HVRCAPUSER\""
          - columnReference:
              columnCounter: 2000252399
              stepCounter: "200023538"
            dataType: VARCHAR
            defaultValue: ""
            description: ""
            name: HVRINTEGKEY
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"LOAD_GW_BC_PROD_BCX_LOCKBOXWORKERCONFIG_EXT\".\"HVRINTEGKEY\""
          - columnReference:
              columnCounter: 2000252400
              stepCounter: "200023538"
            dataType: VARCHAR
            defaultValue: ""
            description: ""
            name: HVRINTEGSEQ
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"STG_ODS_GW_BC_PROD_BCX_LOCKBOXWORKERCONFIG_EXT_05_SEQNO\".\"HVRINTEGSEQ\""
          - columnReference:
              columnCounter: 2000252401
              stepCounter: "200023538"
            dataType: TIMESTAMP
            defaultValue: ""
            description: ""
            name: HVRINTEGTSTAMP
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"LOAD_GW_BC_PROD_BCX_LOCKBOXWORKERCONFIG_EXT\".\"HVRINTEGTSTAMP\""
          - columnReference:
              columnCounter: 2000252402
              stepCounter: "200023538"
            dataType: NUMBER(38)
            defaultValue: ""
            description: ""
            name: HVROP
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"LOAD_GW_BC_PROD_BCX_LOCKBOXWORKERCONFIG_EXT\".\"HVROP\""
          - columnReference:
              columnCounter: 2000252403
              stepCounter: "200023538"
            dataType: NUMBER(38)
            defaultValue: ""
            description: ""
            name: HVRTXCOUNTDOWN
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"LOAD_GW_BC_PROD_BCX_LOCKBOXWORKERCONFIG_EXT\".\"HVRTXCOUNTDOWN\""
          - columnReference:
              columnCounter: 2000252404
              stepCounter: "200023538"
            dataType: VARCHAR
            defaultValue: ""
            description: ""
            name: HVRTXSEQ
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"LOAD_GW_BC_PROD_BCX_LOCKBOXWORKERCONFIG_EXT\".\"HVRTXSEQ\""
          - columnReference:
              columnCounter: 2000252405
              stepCounter: "200023538"
            dataType: VARCHAR(256)
            defaultValue: ""
            description: Record source.
            name: DSS_RECORD_SOURCE
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"LOAD_GW_BC_PROD_BCX_LOCKBOXWORKERCONFIG_EXT\".\"DSS_RECORD_SOURCE\""
          - columnReference:
              columnCounter: 2000252406
              stepCounter: "200023538"
            dataType: TIMESTAMP
            defaultValue: ""
            description: Load date.
            name: DSS_LOAD_DATE
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"LOAD_GW_BC_PROD_BCX_LOCKBOXWORKERCONFIG_EXT\".\"DSS_LOAD_DATE\""
          - columnReference:
              columnCounter: 2000252408
              stepCounter: "200023538"
            dataType: TIMESTAMP
            defaultValue: ""
            description: Date and time the row was created in the data warehouse.
            name: DSS_CREATE_TIME
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: CAST(CURRENT_TIMESTAMP AS TIMESTAMP)
          - columnReference:
              columnCounter: 2000252407
              stepCounter: "200023538"
            dataType: TIMESTAMP
            defaultValue: ""
            description: Date and time the row was updated in the data warehouse.
            name: DSS_UPDATE_TIME
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: CAST(CURRENT_TIMESTAMP AS TIMESTAMP)
        sourceMapping:
          - aliases: {}
            customSQL:
              customSQL: ""
            dependencies:
              - locationName: LOAD
                nodeName: LOAD_GW_BC_PROD_BCX_LOCKBOXWORKERCONFIG_EXT
              - locationName: STAGE
                nodeName: STG_ODS_GW_BC_PROD_BCX_LOCKBOXWORKERCONFIG_EXT_05_SEQNO
              - locationName: ODS
                nodeName: ODS_CTRL_HVRCAPTSTAMP
            join:
              joinCondition: "FROM {{ ref('LOAD','LOAD_GW_BC_PROD_BCX_LOCKBOXWORKERCONFIG_EXT') }} \"LOAD_GW_BC_PROD_BCX_LOCKBOXWORKERCONFIG_EXT\" JOIN {{ ref('STAGE','STG_ODS_GW_BC_PROD_BCX_LOCKBOXWORKERCONFIG_EXT_05_SEQNO') }} \"STG_ODS_GW_BC_PROD_BCX_LOCKBOXWORKERCONFIG_EXT_05_SEQNO\"    ON LOAD_GW_BC_PROD_BCX_LOCKBOXWORKERCONFIG_EXT.HVRINTEGSEQ = STG_ODS_GW_BC_PROD_BCX_LOCKBOXWORKERCONFIG_EXT_05_SEQNO.HVRINTEGSEQ  JOIN {{ ref('ODS','ODS_CTRL_HVRCAPTSTAMP') }} \"ODS_CTRL_HVRCAPTSTAMP\"    ON STG_ODS_GW_BC_PROD_BCX_LOCKBOXWORKERCONFIG_EXT_05_SEQNO.HVRCAPTUREKEY = ODS_CTRL_HVRCAPTSTAMP.HVRCAPTUREKEY  "
            name: STG_ODS_GW_BC_PROD_BCX_LOCKBOXWORKERCONFIG_EXT_10_NEW
            noLinkRefs: []
      name: STG_ODS_GW_BC_PROD_BCX_LOCKBOXWORKERCONFIG_EXT_10_NEW
      overrideSQL: false
      sqlType: Stage
      type: sql
    stepCounter: "200023538"
