steps:
  STG_ODS_GW_BC_PROD_BC_USERSETTINGS_05_SEQNO-200023095:
    operation:
      config:
        insertStrategy: INSERT
        postSQL: ""
        preSQL: ""
        testsEnabled: true
        truncateBefore: true
      database: ""
      dependencies: []
      deployEnabled: true
      description: ""
      isMultisource: false
      locationID: 20000002
      locationName: STAGE
      materializationType: table
      metadata:
        columns:
          - columnReference:
              columnCounter: 2000251202
              stepCounter: "200023095"
            dataType: VARCHAR
            defaultValue: ""
            description: ""
            isBusinessKey: true
            name: HVRINTEGSEQ
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"LOAD_GW_BC_PROD_BC_USERSETTINGS\".\"HVRINTEGSEQ\""
          - columnReference:
              columnCounter: 2000251206
              stepCounter: "200023095"
            dataType: VARCHAR(50)
            defaultValue: ""
            description: ""
            name: HVRCAPTUREKEY
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: "'BC_PROD'"
          - columnReference:
              columnCounter: 2000251205
              stepCounter: "200023095"
            dataType: NUMBER
            defaultValue: ""
            description: Historical Refresh SEQNO for the HVR Table within the specified window
            isBusinessKey: true
            name: HVR_REFRESH_SEQNO
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"ODS_CTRL_HVRREFRESH_HISTORY\".\"HVR_REFRESH_SEQNO_HIST\""
          - columnReference:
              columnCounter: 2000251207
              stepCounter: "200023095"
            dataType: VARCHAR
            defaultValue: ""
            description: ""
            name: HVRINTEGSEQ_ODS
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"ODS_GW_BC_PROD_BC_USERSETTINGS\".\"HVRINTEGSEQ\""
          - columnReference:
              columnCounter: 2000251204
              stepCounter: "200023095"
            dataType: TIMESTAMP
            defaultValue: ""
            description: Date and time the row was created in the data warehouse.
            name: DSS_CREATE_TIME
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: CAST(CURRENT_TIMESTAMP AS TIMESTAMP)
          - columnReference:
              columnCounter: 2000251203
              stepCounter: "200023095"
            dataType: TIMESTAMP
            defaultValue: ""
            description: Date and time the row was updated in the data warehouse.
            name: DSS_UPDATE_TIME
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: CAST(CURRENT_TIMESTAMP AS TIMESTAMP)
        sourceMapping:
          - aliases: {}
            customSQL:
              customSQL: ""
            dependencies:
              - locationName: LOAD
                nodeName: LOAD_GW_BC_PROD_BC_USERSETTINGS
              - locationName: ODS
                nodeName: ODS_CTRL_HVRREFRESH_HISTORY
            join:
              joinCondition: "FROM {{ ref('LOAD','LOAD_GW_BC_PROD_BC_USERSETTINGS') }} \"LOAD_GW_BC_PROD_BC_USERSETTINGS\" JOIN {{ ref('ODS','ODS_CTRL_HVRREFRESH_HISTORY') }} \"ODS_CTRL_HVRREFRESH_HISTORY\"    ON LOAD_GW_BC_PROD_BC_USERSETTINGS.DSS_RECORD_SOURCE = ODS_CTRL_HVRREFRESH_HISTORY.HVR_RECORD_SOURCE  AND LOAD_GW_BC_PROD_BC_USERSETTINGS.HVRCAPTSTAMP BETWEEN ODS_CTRL_HVRREFRESH_HISTORY.FROM_DATE AND ODS_CTRL_HVRREFRESH_HISTORY.THRU_DATE  LEFT JOIN {{ ref_no_link('ODS','ODS_GW_BC_PROD_BC_USERSETTINGS') }} \"ODS_GW_BC_PROD_BC_USERSETTINGS\"  ON LOAD_GW_BC_PROD_BC_USERSETTINGS.HVRINTEGSEQ = ODS_GW_BC_PROD_BC_USERSETTINGS.HVRINTEGSEQ  AND ODS_CTRL_HVRREFRESH_HISTORY.HVR_REFRESH_SEQNO_HIST = ODS_GW_BC_PROD_BC_USERSETTINGS.HVR_REFRESH_SEQNO WHERE ODS_GW_BC_PROD_BC_USERSETTINGS.HVRINTEGSEQ IS NULL "
            name: STG_ODS_GW_BC_PROD_BC_USERSETTINGS_05_SEQNO
            noLinkRefs:
              - locationName: ODS
                nodeName: ODS_GW_BC_PROD_BC_USERSETTINGS
      name: STG_ODS_GW_BC_PROD_BC_USERSETTINGS_05_SEQNO
      overrideSQL: false
      sqlType: Stage
      type: sql
    stepCounter: "200023095"
