steps:
  STG_ODS_GW_BC_PROD_BC_USERSETTINGS_10_NEW-200023096:
    operation:
      config:
        insertStrategy: INSERT
        postSQL: ""
        preSQL: ""
        testsEnabled: true
        truncateBefore: true
      database: ""
      dependencies: []
      deployEnabled: true
      description: ""
      isMultisource: false
      locationID: 20000002
      locationName: STAGE
      materializationType: table
      metadata:
        columns:
          - columnReference:
              columnCounter: 2000251208
              stepCounter: "200023096"
            dataType: BOOLEAN
            defaultValue: ""
            description: ""
            name: ROTATETABLES
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"LOAD_GW_BC_PROD_BC_USERSETTINGS\".\"ROTATETABLES\""
          - columnReference:
              columnCounter: 2000251209
              stepCounter: "200023096"
            dataType: NUMBER(38)
            defaultValue: ""
            description: ""
            name: LOADCOMMANDID
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"LOAD_GW_BC_PROD_BC_USERSETTINGS\".\"LOADCOMMANDID\""
          - columnReference:
              columnCounter: 2000251210
              stepCounter: "200023096"
            dataType: NUMBER(38)
            defaultValue: ""
            description: ""
            name: CREATEUSERID
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"LOAD_GW_BC_PROD_BC_USERSETTINGS\".\"CREATEUSERID\""
          - columnReference:
              columnCounter: 2000251211
              stepCounter: "200023096"
            dataType: VARCHAR(64)
            defaultValue: ""
            description: ""
            name: PUBLICID
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"LOAD_GW_BC_PROD_BC_USERSETTINGS\".\"PUBLICID\""
          - columnReference:
              columnCounter: 2000251212
              stepCounter: "200023096"
            dataType: NUMBER(38)
            defaultValue: ""
            description: ""
            name: BEANVERSION
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"LOAD_GW_BC_PROD_BC_USERSETTINGS\".\"BEANVERSION\""
          - columnReference:
              columnCounter: 2000251213
              stepCounter: "200023096"
            dataType: TIMESTAMP
            defaultValue: ""
            description: ""
            name: CANCELALERTDISMISS
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"LOAD_GW_BC_PROD_BC_USERSETTINGS\".\"CANCELALERTDISMISS\""
          - columnReference:
              columnCounter: 2000251214
              stepCounter: "200023096"
            dataType: BOOLEAN
            defaultValue: ""
            description: ""
            name: PRINTPAGENUMS
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"LOAD_GW_BC_PROD_BC_USERSETTINGS\".\"PRINTPAGENUMS\""
          - columnReference:
              columnCounter: 2000251215
              stepCounter: "200023096"
            dataType: NUMBER(38)
            defaultValue: ""
            description: ""
            name: RETIRED
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"LOAD_GW_BC_PROD_BC_USERSETTINGS\".\"RETIRED\""
          - columnReference:
              columnCounter: 2000251216
              stepCounter: "200023096"
            dataType: TIMESTAMP
            defaultValue: ""
            description: ""
            name: CREATETIME
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"LOAD_GW_BC_PROD_BC_USERSETTINGS\".\"CREATETIME\""
          - columnReference:
              columnCounter: 2000251217
              stepCounter: "200023096"
            dataType: VARCHAR
            defaultValue: ""
            description: ""
            name: LASTPOLICYPERIODS
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"LOAD_GW_BC_PROD_BC_USERSETTINGS\".\"LASTPOLICYPERIODS\""
          - columnReference:
              columnCounter: 2000251218
              stepCounter: "200023096"
            dataType: VARCHAR
            defaultValue: ""
            description: ""
            name: LASTPRODUCERS
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"LOAD_GW_BC_PROD_BC_USERSETTINGS\".\"LASTPRODUCERS\""
          - columnReference:
              columnCounter: 2000251219
              stepCounter: "200023096"
            dataType: NUMBER(38)
            defaultValue: ""
            description: ""
            name: STARTUPPAGE
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"LOAD_GW_BC_PROD_BC_USERSETTINGS\".\"STARTUPPAGE\""
          - columnReference:
              columnCounter: 2000251220
              stepCounter: "200023096"
            dataType: NUMBER(38)
            defaultValue: ""
            description: ""
            name: UPDATEUSERID
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"LOAD_GW_BC_PROD_BC_USERSETTINGS\".\"UPDATEUSERID\""
          - columnReference:
              columnCounter: 2000251221
              stepCounter: "200023096"
            dataType: TIMESTAMP
            defaultValue: ""
            description: ""
            name: UPDATETIME
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"LOAD_GW_BC_PROD_BC_USERSETTINGS\".\"UPDATETIME\""
          - columnReference:
              columnCounter: 2000251222
              stepCounter: "200023096"
            dataType: BOOLEAN
            defaultValue: ""
            description: ""
            name: SHOWPRINTPREVIEW
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"LOAD_GW_BC_PROD_BC_USERSETTINGS\".\"SHOWPRINTPREVIEW\""
          - columnReference:
              columnCounter: 2000251223
              stepCounter: "200023096"
            dataType: NUMBER(2,1)
            defaultValue: ""
            description: ""
            name: PRINTMARGINS
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"LOAD_GW_BC_PROD_BC_USERSETTINGS\".\"PRINTMARGINS\""
          - columnReference:
              columnCounter: 2000251224
              stepCounter: "200023096"
            dataType: NUMBER(38)
            defaultValue: ""
            description: ""
            name: ID
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"LOAD_GW_BC_PROD_BC_USERSETTINGS\".\"ID\""
          - columnReference:
              columnCounter: 2000251225
              stepCounter: "200023096"
            dataType: VARCHAR
            defaultValue: ""
            description: ""
            name: LASTACCOUNTS
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"LOAD_GW_BC_PROD_BC_USERSETTINGS\".\"LASTACCOUNTS\""
          - columnReference:
              columnCounter: 2000251226
              stepCounter: "200023096"
            dataType: VARCHAR
            defaultValue: ""
            description: ""
            name: HVRCAPLOC
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"LOAD_GW_BC_PROD_BC_USERSETTINGS\".\"HVRCAPLOC\""
          - columnReference:
              columnCounter: 2000251227
              stepCounter: "200023096"
            dataType: TIMESTAMP
            defaultValue: ""
            description: ""
            name: HVRCAPTSTAMP
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"LOAD_GW_BC_PROD_BC_USERSETTINGS\".\"HVRCAPTSTAMP\""
          - columnReference:
              columnCounter: 2000251228
              stepCounter: "200023096"
            dataType: TIMESTAMP
            defaultValue: ""
            description: ""
            name: HVRCAPTSTAMPUTC
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"LOAD_GW_BC_PROD_BC_USERSETTINGS\".\"HVRCAPTSTAMPUTC\""
          - columnReference:
              columnCounter: 2000251240
              stepCounter: "200023096"
            dataType: VARCHAR(50)
            defaultValue: ""
            description: ""
            name: HVRCAPTUREKEY
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"STG_ODS_GW_BC_PROD_BC_USERSETTINGS_05_SEQNO\".\"HVRCAPTUREKEY\""
          - columnReference:
              columnCounter: 2000251241
              stepCounter: "200023096"
            dataType: NUMBER
            defaultValue: ""
            description: Historical Refresh SEQNO for the HVR Table within the specified window
            name: HVR_REFRESH_SEQNO
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"STG_ODS_GW_BC_PROD_BC_USERSETTINGS_05_SEQNO\".\"HVR_REFRESH_SEQNO\""
          - columnReference:
              columnCounter: 2000251242
              stepCounter: "200023096"
            dataType: VARCHAR(15)
            defaultValue: ""
            description: Batch Number for the Process Cycle
            name: BATCH_NUMBER
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"ODS_CTRL_HVRCAPTSTAMP\".\"BATCH_NUMBER\""
          - columnReference:
              columnCounter: 2000251229
              stepCounter: "200023096"
            dataType: VARCHAR
            defaultValue: ""
            description: ""
            name: HVRCAPUSER
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"LOAD_GW_BC_PROD_BC_USERSETTINGS\".\"HVRCAPUSER\""
          - columnReference:
              columnCounter: 2000251230
              stepCounter: "200023096"
            dataType: VARCHAR
            defaultValue: ""
            description: ""
            name: HVRINTEGKEY
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"LOAD_GW_BC_PROD_BC_USERSETTINGS\".\"HVRINTEGKEY\""
          - columnReference:
              columnCounter: 2000251231
              stepCounter: "200023096"
            dataType: VARCHAR
            defaultValue: ""
            description: ""
            name: HVRINTEGSEQ
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"STG_ODS_GW_BC_PROD_BC_USERSETTINGS_05_SEQNO\".\"HVRINTEGSEQ\""
          - columnReference:
              columnCounter: 2000251232
              stepCounter: "200023096"
            dataType: TIMESTAMP
            defaultValue: ""
            description: ""
            name: HVRINTEGTSTAMP
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"LOAD_GW_BC_PROD_BC_USERSETTINGS\".\"HVRINTEGTSTAMP\""
          - columnReference:
              columnCounter: 2000251233
              stepCounter: "200023096"
            dataType: NUMBER(38)
            defaultValue: ""
            description: ""
            name: HVROP
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"LOAD_GW_BC_PROD_BC_USERSETTINGS\".\"HVROP\""
          - columnReference:
              columnCounter: 2000251234
              stepCounter: "200023096"
            dataType: NUMBER(38)
            defaultValue: ""
            description: ""
            name: HVRTXCOUNTDOWN
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"LOAD_GW_BC_PROD_BC_USERSETTINGS\".\"HVRTXCOUNTDOWN\""
          - columnReference:
              columnCounter: 2000251235
              stepCounter: "200023096"
            dataType: VARCHAR
            defaultValue: ""
            description: ""
            name: HVRTXSEQ
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"LOAD_GW_BC_PROD_BC_USERSETTINGS\".\"HVRTXSEQ\""
          - columnReference:
              columnCounter: 2000251236
              stepCounter: "200023096"
            dataType: VARCHAR(256)
            defaultValue: ""
            description: Record source.
            name: DSS_RECORD_SOURCE
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"LOAD_GW_BC_PROD_BC_USERSETTINGS\".\"DSS_RECORD_SOURCE\""
          - columnReference:
              columnCounter: 2000251237
              stepCounter: "200023096"
            dataType: TIMESTAMP
            defaultValue: ""
            description: Load date.
            name: DSS_LOAD_DATE
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"LOAD_GW_BC_PROD_BC_USERSETTINGS\".\"DSS_LOAD_DATE\""
          - columnReference:
              columnCounter: 2000251239
              stepCounter: "200023096"
            dataType: TIMESTAMP
            defaultValue: ""
            description: Date and time the row was created in the data warehouse.
            name: DSS_CREATE_TIME
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: CAST(CURRENT_TIMESTAMP AS TIMESTAMP)
          - columnReference:
              columnCounter: 2000251238
              stepCounter: "200023096"
            dataType: TIMESTAMP
            defaultValue: ""
            description: Date and time the row was updated in the data warehouse.
            name: DSS_UPDATE_TIME
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: CAST(CURRENT_TIMESTAMP AS TIMESTAMP)
        sourceMapping:
          - aliases: {}
            customSQL:
              customSQL: ""
            dependencies:
              - locationName: LOAD
                nodeName: LOAD_GW_BC_PROD_BC_USERSETTINGS
              - locationName: STAGE
                nodeName: STG_ODS_GW_BC_PROD_BC_USERSETTINGS_05_SEQNO
              - locationName: ODS
                nodeName: ODS_CTRL_HVRCAPTSTAMP
            join:
              joinCondition: "FROM {{ ref('LOAD','LOAD_GW_BC_PROD_BC_USERSETTINGS') }} \"LOAD_GW_BC_PROD_BC_USERSETTINGS\" JOIN {{ ref('STAGE','STG_ODS_GW_BC_PROD_BC_USERSETTINGS_05_SEQNO') }} \"STG_ODS_GW_BC_PROD_BC_USERSETTINGS_05_SEQNO\"    ON LOAD_GW_BC_PROD_BC_USERSETTINGS.HVRINTEGSEQ = STG_ODS_GW_BC_PROD_BC_USERSETTINGS_05_SEQNO.HVRINTEGSEQ  JOIN {{ ref('ODS','ODS_CTRL_HVRCAPTSTAMP') }} \"ODS_CTRL_HVRCAPTSTAMP\"    ON STG_ODS_GW_BC_PROD_BC_USERSETTINGS_05_SEQNO.HVRCAPTUREKEY = ODS_CTRL_HVRCAPTSTAMP.HVRCAPTUREKEY  "
            name: STG_ODS_GW_BC_PROD_BC_USERSETTINGS_10_NEW
            noLinkRefs: []
      name: STG_ODS_GW_BC_PROD_BC_USERSETTINGS_10_NEW
      overrideSQL: false
      sqlType: Stage
      type: sql
    stepCounter: "200023096"
